# This is a basic workflow that is manually triggered

name: build release
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      flavor:
        type: choice
        description: 'Debian Version'
        options:
          - 'trixie'
          - 'bookworm'
          - 'bullseye'
          - 'buster'
        required: true
      version_tag:
        description: 'Version Tag'
        default: '6.12'
        required: true
      release:
        type: boolean
        description: "publish to repository"

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: "smeinecke/aufs-dkms-build:${{ github.event.inputs.flavor }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Run build script
        run: ./scripts/build.sh
        env:
          DEB_FLAVOR: "${{ github.event.inputs.flavor }}"
          VERSION_TAG: "${{ github.event.inputs.version_tag }}"
      - name: Upload deb files
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: packages-${{ github.event.inputs.flavor }}
          path: ./*.deb
      - name: Release
        if: github.event.inputs.release && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@e598afbe1493e6b1bafb1f389cabb956eab91231 # v3.0.3
        with:
          files: ./*.deb
      - name: Github pages APT repo
        if: github.event.inputs.release
        uses: smeinecke/apt-repo-action@b12d0c7cf1297211dbdf15c05b1dba5849ede9bb # v2.1.8
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo_supported_arch: amd64
          repo_supported_version: |
            buster
            bullseye
            bookworm
            trixie
          file: |
            *.deb
          file_target_version: "${{ github.event.inputs.flavor }}"
          public_key: ${{ secrets.APT_PUBLIC_KEY }}
          private_key: ${{ secrets.APT_SIGNING_KEY }}
          key_passphrase: ""
